In [0]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [0]:
# try:
#   # %tensorflow_version only exists in Colab.
#   %tensorflow_version 2.x
# except Exception:
#   pass

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.1.0


In [2]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
   print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [3]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [4]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [6]:
dataset = tf.data.Dataset.range(30)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]
[ 6  7  8  9 10]
[ 7  8  9 10 11]
[ 8  9 10 11 12]
[ 9 10 11 12 13]
[10 11 12 13 14]
[11 12 13 14 15]
[12 13 14 15 16]
[13 14 15 16 17]
[14 15 16 17 18]
[15 16 17 18 19]
[16 17 18 19 20]
[17 18 19 20 21]
[18 19 20 21 22]
[19 20 21 22 23]
[20 21 22 23 24]
[21 22 23 24 25]
[22 23 24 25 26]
[23 24 25 26 27]
[24 25 26 27 28]
[25 26 27 28 29]


In [7]:
dataset = tf.data.Dataset.range(30)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]
[6 7 8 9] [10]
[ 7  8  9 10] [11]
[ 8  9 10 11] [12]
[ 9 10 11 12] [13]
[10 11 12 13] [14]
[11 12 13 14] [15]
[12 13 14 15] [16]
[13 14 15 16] [17]
[14 15 16 17] [18]
[15 16 17 18] [19]
[16 17 18 19] [20]
[17 18 19 20] [21]
[18 19 20 21] [22]
[19 20 21 22] [23]
[20 21 22 23] [24]
[21 22 23 24] [25]
[22 23 24 25] [26]
[23 24 25 26] [27]
[24 25 26 27] [28]
[25 26 27 28] [29]


In [22]:
dataset = tf.data.Dataset.range(30)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy(), y.numpy())

[6 7 8 9] [10]
[10 11 12 13] [14]
[ 8  9 10 11] [12]
[1 2 3 4] [5]
[11 12 13 14] [15]
[2 3 4 5] [6]
[14 15 16 17] [18]
[13 14 15 16] [17]
[17 18 19 20] [21]
[0 1 2 3] [4]
[4 5 6 7] [8]
[5 6 7 8] [9]
[20 21 22 23] [24]
[12 13 14 15] [16]
[ 7  8  9 10] [11]
[18 19 20 21] [22]
[ 9 10 11 12] [13]
[3 4 5 6] [7]
[23 24 25 26] [27]
[25 26 27 28] [29]
[15 16 17 18] [19]
[19 20 21 22] [23]
[16 17 18 19] [20]
[21 22 23 24] [25]
[24 25 26 27] [28]
[22 23 24 25] [26]


In [20]:
dataset = tf.data.Dataset.range(30)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
# dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(0)
for x,y in dataset:
  print("x = ", x.numpy().tolist(), " --> y = ", y.numpy().tolist())

x =  [[0, 1, 2, 3], [1, 2, 3, 4]]  --> y =  [[4], [5]]
x =  [[2, 3, 4, 5], [3, 4, 5, 6]]  --> y =  [[6], [7]]
x =  [[4, 5, 6, 7], [5, 6, 7, 8]]  --> y =  [[8], [9]]
x =  [[6, 7, 8, 9], [7, 8, 9, 10]]  --> y =  [[10], [11]]
x =  [[8, 9, 10, 11], [9, 10, 11, 12]]  --> y =  [[12], [13]]
x =  [[10, 11, 12, 13], [11, 12, 13, 14]]  --> y =  [[14], [15]]
x =  [[12, 13, 14, 15], [13, 14, 15, 16]]  --> y =  [[16], [17]]
x =  [[14, 15, 16, 17], [15, 16, 17, 18]]  --> y =  [[18], [19]]
x =  [[16, 17, 18, 19], [17, 18, 19, 20]]  --> y =  [[20], [21]]
x =  [[18, 19, 20, 21], [19, 20, 21, 22]]  --> y =  [[22], [23]]
x =  [[20, 21, 22, 23], [21, 22, 23, 24]]  --> y =  [[24], [25]]
x =  [[22, 23, 24, 25], [23, 24, 25, 26]]  --> y =  [[26], [27]]
x =  [[24, 25, 26, 27], [25, 26, 27, 28]]  --> y =  [[28], [29]]
